name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present

    # Deploy only on push to master and only once (not for each matrix version)
    - name: Set Git identity for deploy
      if: github.ref == 'refs/heads/master' && matrix.node-version == '22.x'
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/master' && matrix.node-version == '22.x'
      run: npm run deploy
